# Generated by Django 6.0.7 on 2026-08-12 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_enforce_session_file_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_ref', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('held', 'Held in Escrow'), ('released', 'Released to Expert'), ('refunded', 'Refunded to Client'), ('failed', 'Payment Failed')], default='initiated', max_length=20)),
                ('chapa_checkout_url', models.URLField(blank=True, max_length=500, null=True)),
                ('raw_provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transaction', to='bookings.booking')),
            ],
            options={
                'db_table': 'payments_escrow_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
