# Generated by Django 6.0.7 on 2026-07-29 16:13

import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='LegalDocumentEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('doc_reference', models.CharField(help_text='e.g. Startup Proclamation No. 1396/2025', max_length=255)),
                ('content_chunk', models.TextField()),
                ('category', models.CharField(help_text='e.g. tax, startup_law, fx_law', max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_legal_document_embedding',
                'indexes': [models.Index(fields=['embedding'], name='legal_doc_vec_hnsw_idx')],
            },
        ),
    ]
