# Generated by Django 6.0.7 on 2026-07-29 16:28

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='legaldocumentembedding',
            name='legal_doc_vec_hnsw_idx',
        ),
        migrations.AddIndex(
            model_name='legaldocumentembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='legal_doc_vec_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
