# Generated by Django 6.0.7 on 2026-07-30 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_remove_legaldocumentembedding_legal_doc_vec_hnsw_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('context_type', models.CharField(choices=[('ai_chat', 'AI Chat'), ('session_chat', 'Session Chat')], default='ai_chat', max_length=20)),
                ('role', models.CharField(choices=[('user', 'User'), ('expert', 'Expert'), ('ai', 'AI'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking_id', 'sender', 'created_at'], name='chat_messag_booking_4f3f16_idx')],
            },
        ),
    ]
