# Generated by Django 6.0.7 on 2026-08-05 23:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocumentembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
    ]
