# Generated by Django 6.0.7 on 2026-09-04 16:20

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_service", "0006_chatsessionmetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocumentembedding",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
    ]
