# Generated by Django 6.0.7 on 2026-08-03 07:52

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('specialty_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="e.g. ['tax', 'startup_law', 'commercial_code']")),
                ('rate_per_session', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('wallet_provider', models.CharField(choices=[('telebirr', 'Telebirr'), ('cbe_birr', 'CBE Birr'), ('mpesa', 'M-Pesa')], default='telebirr', max_length=20)),
                ('wallet_account_number', models.CharField(blank=True, max_length=100)),
                ('availability', models.JSONField(blank=True, default=dict, help_text="Weekly availability slots matrix e.g. {'mon': ['09:00-12:00']}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experts_expert',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['specialty_tags'], name='expert_specialty_tags_gin'), models.Index(fields=['verification_status'], name='experts_exp_verific_ddf219_idx')],
            },
        ),
    ]
