# Generated by Django 6.0.7 on 2026-08-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
