# Generated by Django 6.0.7 on 2026-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_alter_expert_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
