# Generated by Django 6.0.7 on 2026-08-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_expert_license_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated net payout earnings', max_digits=12),
        ),
    ]
