# Generated by Django 6.0.7 on 2026-08-04 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video'), ('chat', 'Chat')], default='voice', max_length=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('escrowed', 'Escrowed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='pending_payment', max_length=20)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField(db_index=True)),
                ('rate_snapshot', models.DecimalField(decimal_places=2, help_text='Flat rate or per-session snapshot locked at booking time.', max_digits=10)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_bookings', to='experts.expert')),
            ],
            options={
                'db_table': 'bookings_booking',
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['expert', 'scheduled_start', 'scheduled_end'], name='idx_booking_expert_schedule'), models.Index(fields=['client', 'status'], name='idx_booking_client_status')],
            },
        ),
    ]
