# Generated by Django 6.0.7 on 2026-08-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_sessionfile'),
    ]

    operations = [
        # 1. Enable RLS on bookings_session_file
        migrations.RunSQL(
            sql="ALTER TABLE bookings_session_file ENABLE ROW LEVEL SECURITY;",
            reverse_sql="ALTER TABLE bookings_session_file DISABLE ROW LEVEL SECURITY;"
        ),
        # 2. Add isolation policy allowing only booking client, booking expert user, or admin
        migrations.RunSQL(
            sql="""
            CREATE POLICY session_file_participant_policy ON bookings_session_file
            FOR ALL
            USING (
                uploader_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
                OR EXISTS (
                    SELECT 1 FROM bookings_booking b
                    JOIN experts_expert e ON b.expert_id = e.id
                    WHERE b.id = bookings_session_file.booking_id
                    AND (
                        b.client_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
                        OR e.user_id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
                    )
                )
                OR EXISTS (
                    SELECT 1 FROM users_user u
                    WHERE u.id = NULLIF(current_setting('app.current_user_id', true), '')::uuid
                    AND u.is_staff = TRUE
                )
            );
            """,
            reverse_sql="DROP POLICY IF EXISTS session_file_participant_policy ON bookings_session_file;"
        ),
    ]
