# Generated by Django 6.0.7 on 2026-08-13 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('sms', 'SMS Gateway'), ('push', 'Push Notification'), ('in_app', 'In-App Drawer')], default='sms', max_length=20)),
                ('notification_type', models.CharField(choices=[('reminder_24h', '24-Hour Reminder'), ('reminder_1h', '1-Hour Reminder'), ('schedule_change', 'Schedule Updated'), ('cancellation', 'Booking Cancelled')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-sent_at'],
            },
        ),
    ]
