# Generated by Django 6.0.7 on 2026-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder_24h', '24-Hour Reminder'), ('reminder_1h', '1-Hour Reminder'), ('schedule_change', 'Schedule Updated'), ('cancellation', 'Booking Cancelled'), ('new_booking', 'New Booking')], max_length=30),
        ),
    ]
